# Generated by Django 4.2rc1 on 2023-04-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Account number')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userprofile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Card number')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account', verbose_name='Account number')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
