# Generated by Django 4.2b1 on 2023-03-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Account number')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userprofile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
