# Generated by Django 4.2rc1 on 2023-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_card', models.PositiveBigIntegerField(verbose_name='From card number')),
                ('to_card', models.PositiveBigIntegerField(verbose_name='To card number')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
