# Generated by Django 4.2b1 on 2023-03-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Card number')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account', verbose_name='Account number')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
