# Generated by Django 4.2a1 on 2023-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
