# Generated by Django 4.2rc1 on 2023-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='user ID')),
                ('favourite_user_id', models.PositiveIntegerField(unique=True, verbose_name='favourite user telegram ID')),
            ],
            options={
                'verbose_name': 'Favourite user',
                'verbose_name_plural': 'Favourite users',
            },
        ),
    ]
