# Generated by Django 4.2rc1 on 2023-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_favouriteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteuser',
            name='favourite_user_id',
            field=models.PositiveIntegerField(verbose_name='favourite user telegram ID'),
        ),
        migrations.AlterField(
            model_name='favouriteuser',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='user ID'),
        ),
    ]
