# Generated by Django 4.2b1 on 2023-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Account number')),
                ('telegram_id', models.PositiveIntegerField(verbose_name='telegram ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Card number')),
                ('account_number', models.PositiveBigIntegerField(verbose_name='Account number')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
