# Generated by Django 4.2rc1 on 2023-04-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'Favorite user',
                'verbose_name_plural': 'Favorite users',
            },
        ),
    ]
