# Generated by Django 4.2b1 on 2023-03-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account'),
        ),
    ]
