# Generated by Django 4.2b1 on 2023-03-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userprofile', verbose_name='User profile'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account', verbose_name='Account number'),
        ),
    ]
