# Generated by Django 4.2b1 on 2023-03-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_account_telegram_id_remove_card_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='account_number',
            new_name='account',
        ),
    ]
