default:
  tags:
    - build
    - deploy

stages:
  - build
  - deploy
  

build:
  stage: build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - echo $CI_REGISTRY_USER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/bot-app:1 .
    - docker push $CI_REGISTRY/bot-app:1

deploy:
  stage: deploy
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/bot-app:1
    - docker compose down
    - docker compose up -d