default:
  tags:
    - build
    - deploy

stages:
  - build
  - deploy
  

build:
  stage: build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - echo $CI_REGISTRY_USER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_NAME
    - docker compose down
    - docker compose up -d