stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  tags:
    - job:build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - echo $CI_REGISTRY_USER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t frogfrog243/bot-app:1 .
    - docker push frogfrog243/bot-app:1
  only:
    - main
  environment:
    name: prod

lint:
  stage: lint
  tags:
    - job:lint
  script:
    - echo "lint"
  only:
    - main
  environment:
    name: prod

test:
  stage: test
  tags:
    - job:test
  script:
    - echo "test"
  only:
    - main
  environment:
    name: prod

deploy:
  stage: deploy
  tags:
    - job:deploy
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull frogfrog243/bot-app:1
    - docker compose down
    - docker compose up -d
  only:
    - main
  environment:
    name: prod