image: docker/compose:alpine-1.28.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build
  tags:
    - build
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker compose up
  tags:
    - deploy
  only:
    - master
  environment:
    name: prod

