stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  tags:
    - build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - make build
  only:
    - main
  environment:
    name: prod

lint:
  stage: lint
  tags:
    - lint
  script:
    - echo "lint'
  only:
    - main
  environment:
    name: prod

test:
  stage: test
  tags:
    - test
  script:
    - make test
  only:
    - main
  environment:
    name: prod
 
deploy:
  stage: deploy
  tags:
    - deploy
  script: 
    - make up
  only:
    - main 
  environment:
    name: prod