default:
  tags:
    - build
    - deploy

stages:
  - build
  - deploy
  

build:
  stage: build
  script:
    - docker build -t bot-app:1 .

deploy:
  stage: deploy
  script: 
    - docker compose down
    - docker compose up