image: docker/compose:alpine-1.28.0

stages:
  - build
  - deploy

before_script:
  - apk add make
  - cp $DOT_ENV $(pwd)/.env

build:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - make pull down migrate up
  tags:
    - job:test
  only:
    - master
  environment:
    name: prod
