image: docker/compose:alpine-1.28.0

stages:
  - build
  - deploy

before_script:
  - apk add make
  - docker login -u "cibinnikita@gmail.com" -p "docker1234"
  - cp $DOT_ENV $(pwd)/.env

build:
  stage: build
  script:
    - docker build
    - docker push
  tags:
    - job:build
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - docker pull
    - docker compose down
    - docker compose up
  tags:
    - job:deploy
  only:
    - master
  environment:
    name: prod

