default:
  tags:
    - build
    - lint
    - test
    - deploy

stages:
  - build
  - lint
  - test
  - deploy
  

build:
  stage: build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - echo $CI_REGISTRY_USER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t frogfrog243/bot-app:1 .
    - docker push frogfrog243/bot-app:1 

lint:
  stage: lint
  script:
    - echo "lint"

test:
  stage: test
  script:
    - echo "test"

deploy:
  stage: deploy
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull frogfrog243/bot-app:1
    - docker compose down
    - docker compose up -d