default:
  tags:
    - build
    - deploy

stages:
  - build
  - deploy
  

build:
  stage: build
  script:
    - touch .env
    - cp $DOT_ENV .env
    - docker login -u ${USER} -p {PASSWORD} ${REGISTRY}
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}

deploy:
  stage: deploy
  script: 
    - docker compose down
    - docker compose up -d