version: "3.9"

volumes:
  data:

services:
  db:
    image: postgres:13.3
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    build: ./src
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  web:
    container_name: app
    image: ${IMAGE_NAME}
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "${PORT}:${PORT}"
    command: python ./src/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  bot:
    container_name: bot
    image: ${IMAGE_NAME}
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    command: python ./src/manage.py bot
    depends_on:
      - db