version: "3.9"

services:
  web:
    container_name: app
    image: bot-app:1
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "8000:8000"
    command: python ./src/manage.py runserver 0.0.0.0:8000

  bot:
    container_name: bot
    image: bot-app:1
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    command: python ./src/manage.py bot