version: "3.9"

services:
  web:
    container_name: app
    image: bot-app:1
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "8090:8090"
    command: python ./src/manage.py runserver 0.0.0.0:8090

  bot:
    container_name: bot
    image: bot-app:1
    build: ./src
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "8443:8443"
    command: python ./src/manage.py bot