version: "3.9"

services:
  web:
    container_name: app
    image: bot-app:1
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "80:8000"
    expose:
      - 8000
    command: python ./src/manage.py runserver 0.0.0.0:8000

  bot:
    container_name: bot
    image: bot-app:1
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/mounted:/opt/file
    ports:
      - "1234:1234"
    expose:
      - 8000
    command: python ./src/manage.py bot